eccomerce/eccomerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('summernote/', include('django_summernote.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eccomerce/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.logout_view,name='logout'),
    path('', views.all_products, name='all_products'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('cart/',views.cart,name='cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('order-confirmation/',views.order_confirmation,name='order_confirmation'),
    path('add_cart/',views.addcart,name='addcart'),
    path('order/',views.order,name='order'),
    path('orderreceived/',views.rozarpayverify,name="orderreceived"),
   


]

eccomerce/store/forms.py
from django import forms
from .models import  *
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control form-control_gray'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control_gray'}))

class SignupForm(forms.Form):
    name = forms.CharField(max_length=100, required=True, label="Full Name", widget=forms.TextInput(attrs={'class': 'form-control form-control_gray'}))
    email = forms.EmailField(required=True, label="Email Address", widget=forms.TextInput(attrs={'class': 'form-control form-control_gray'}))
    mobile = forms.CharField(max_length=15, required=True, label="Mobile Number", widget=forms.TextInput(attrs={'class': 'form-control form-control_gray'}))
    password = forms.CharField(
        required=True, label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control form-control_gray'})
    )
    c_password = forms.CharField(
         required=True, label="Confrim Password", widget=forms.PasswordInput(attrs={'class': 'form-control form-control_gray'})
    )
    captcha = ReCaptchaField(
        widget=ReCaptchaV3(action='signup')
    )


    def clean_email(self):
        email = self.cleaned_data.get('email')
       
      
        
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already registered.")
        return email
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        c_password = cleaned_data.get('c_password')

        if password and c_password and password != c_password:
            raise ValidationError({"c_password": "Passwords do not match."})

        return cleaned_data
    


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=True, label="Full Name", widget=forms.TextInput(attrs={'class': 'form-control form-control_gray'}))
    email = forms.EmailField(required=True, label="Email Address", widget=forms.TextInput(attrs={'class': 'form-control form-control_gray'}))
    mobile = forms.CharField(max_length=15, required=True, label="Mobile Number", widget=forms.TextInput(attrs={'class': 'form-control form-control_gray'}))
    message = forms.CharField(max_length=15, required=True, label="Message", widget=forms.Textarea(attrs={'class': 'form-control form-control_gray'}))
    captcha = ReCaptchaField(widget=ReCaptchaV3(action='signup'))

eccomerce/store/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth import authenticate, login, logout
import razorpay
from django.contrib import messages 
from .models import *
from .forms import *
from django.contrib.auth.hashers import make_password
from django.http import JsonResponse
from django.db.models import Sum
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.conf import settings
from razorpay.errors import BadRequestError
razorpay_client = razorpay.Client(
    auth=(settings.ROZARPAY_KEY, settings.RAZOR_KEY_SECRET))

def cart_sessions(request):
    carts=request.session.session_key 
    print('carts===',carts)
    if not carts:
       carts=request.session.create()
       print(carts)
    return carts  

def user_login(request):
     
  
     if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = authenticate(request, username=email, password=password)
            
            if user is not None  and user.is_active == True:
             
                    try:
                         carts = Cart.objects.all()
                         try:
                                car=CartItem.objects.get(user=user,cart_id__in=[x.id for x in carts])
                                # c1=Cart.objects.all()
                                # c2=CartItem.objects.filter(cart)
                                print('car',car)
                         except CartItem.DoesNotExist:
                                carts = Cart.objects.get(cart_id=cart_sessions(request))
                                cart_exists = CartItem.objects.filter(cart=carts).exists()
                                if cart_exists:
                                    cart_items = CartItem.objects.filter(cart=carts)
                                    for item in cart_items:
                                        item.user = user
                                        item.save()
                    except CartItem.DoesNotExist:
                            carts = Cart.objects.get(cart_id=cart_sessions(request))
                            cart_exists = CartItem.objects.filter(cart=carts).exists()
                            if cart_exists:
                                cart_items = CartItem.objects.filter(cart=carts)
                                for item in cart_items:
                                    item.user = user
                                    item.save()
                
                    login(request, user)
                    return redirect('store:all_products')
            else:
                form = LoginForm()
                return render(request,'store/login.html',{'form':form})

     else:
            form = LoginForm()
            return render(request,'store/login.html',{'form':form})

     return render(request,'store/login.html')


def signup(request):
    if request.method == "POST":
       form = SignupForm(request.POST)
       if form.is_valid():
            User.objects.create(
                email=form.cleaned_data['email'],
                name=form.cleaned_data['name'],
                mobile=form.cleaned_data['mobile'],
                password=make_password(form.cleaned_data['password']),
            )
            return redirect('store:login')  # Replace with your desired redirect
    else:
         form = SignupForm()
         return render(request,'store/signup.html',{'form':form})

      

    return render(request,'store/signup.html',{'form':form})


def logout_view(request):
    logout(request)
    return redirect('store:login')




def all_products(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    if request.user.is_authenticated:
        try:
            cartitem=CartItem.objects.get(product_id=product.id,user=request.user)
        except CartItem.DoesNotExist:
            cartitem=None

    else:
         try:
                cart=Cart.objects.get(cart_id=cart_sessions(request))
                cartitem=CartItem.objects.filter(product_id=product.id,cart_id=cart).exists()
         except Cart.DoesNotExist:
                cart=None
                cartitem=None

    return render(request, 'store/products/detail.html', {'product': product,'cartitem':cartitem})

def about(request):
    return render(request,'store/about.html')

def contact(request):
     contact=ContactForm()
     if request.method == "POST":
       form = ContactForm(request.POST)
       if form.is_valid():
            Contact.objects.create(
                name=form.cleaned_data['name'],
                mobile=form.cleaned_data['mobile'],
                email=form.cleaned_data['email'],
                description=form.cleaned_data['message']),
            
            return redirect('store:contact') 
    
     return render(request,'store/contact.html',{'contact':contact})

def cart(request):
    rozarpay_key="rzp_test_7UQe0QqyW56WC6"

    if request.user.is_authenticated:
         carts=Cart.objects.all()

         cartitem=CartItem.objects.filter(user=request.user,cart_id__in=[x.id for x in carts])
         print(cartitem)
         totalcart=CartItem.objects.filter(cart_id__in=[x.id for x in carts],user=request.user)
         totalcartitems=totalcart.aggregate(product_price=Sum('product__price'))
         
         totalgst=totalcartitems.get('product_price') * 18 / 100
         totalsum=totalcartitems.get('product_price')  + totalgst
    else:
         
         
         carts=Cart.objects.get(cart_id=cart_sessions(request))
         cartitem=CartItem.objects.filter(cart_id=carts)
         totalcart=CartItem.objects.filter(cart_id=carts)
         totalcartitems=totalcart.aggregate(product_price=Sum('product__price'))
         
         totalgst=totalcartitems.get('product_price') * 18 / 100
         totalsum=totalcartitems.get('product_price')  + totalgst
    return render(request,'store/cart.html',{'rozarpay_key':rozarpay_key,'cartitem':cartitem,'totalcartitems':totalcartitems,'totalsum':totalsum})

def checkout(request):
    if request.user.is_authenticated:
            rozarpay_key="rzp_test_7UQe0QqyW56WC6"
            currency='INR'
            base_url="http://127.0.0.1:8000"
            callback_url = 'orderreceived/'
            user=User.objects.get(email=request.user)
            carts=Cart.objects.all()
            cartitem=CartItem.objects.filter(user=request.user,cart_id__in=[x.id for x in carts])
          
            totalcart=CartItem.objects.filter(cart_id__in=[x.id for x in carts],user=request.user)
            totalcartitems=totalcart.aggregate(product_price=Sum('product__price'))
                
            totalgst=totalcartitems.get('product_price') * 18 / 100
            totalsum=totalcartitems.get('product_price')  + totalgst
            amount=int(totalsum)
    # else:
    #         rozarpay_key="rzp_test_7UQe0QqyW56WC6"
    #         currency='INR'
    #         base_url="http://127.0.0.1:8000"
    #         callback_url = 'orderreceived/'
    #         user=User.objects.get(email=request.user)
    #         carts=Cart.objects.all()
    #         cartitem=CartItem.objects.filter(user=request.user,cart_id__in=[x.id for x in carts])
    #         print(cartitem)
    #         totalcart=CartItem.objects.filter(cart_id__in=[x.id for x in carts],user=request.user)
    #         totalcartitems=totalcart.aggregate(product_price=Sum('product__price'))
                
    #         totalgst=totalcartitems.get('product_price') * 18 / 100
    #         totalsum=totalcartitems.get('product_price')  + totalgst
    currency="INR"
    try:
                razorpay_order = razorpay_client.order.create(dict(amount=amount*100, currency=currency,payment_capture='0'))
                print('razorpay_order',razorpay_order)
    except BadRequestError as e:
                amount=1.00
                razorpay_order = razorpay_client.order.create(dict( amount=int(amount * 100),   currency='INR', payment_capture='0'))
    razorpay_order_id = razorpay_order['id']
    request.session['razorpay_order_id'] = razorpay_order_id
    rozarpay_key=settings.ROZARPAY_KEY
    
    return render(request,'store/checkout.html',{'razorpay_order_id':razorpay_order_id,'rozarpay_key':rozarpay_key,"base_url":base_url,"callback_url":callback_url,'currency':currency,'rozarpay_key':rozarpay_key,'user':user,'cartitem':cartitem,'totalcartitems':totalcartitems,'totalsum':totalsum,'totalgst':totalgst})


def order_confirmation(request):
    return render(request,'store/order-confirmation.html')


def addcart(request):
      
      if request.method == "POST":
            print('okkkk addcart ===========================')
            product_id=request.POST.get('product_id')
            prod=Product.objects.get(id=product_id)
            if request.user.is_authenticated:
            
                cartitem1=CartItem.objects.filter(user=request.user)
                if Cart.objects.filter(cart_id__in=[x.cart for x in cartitem1]).exists():
                    print('okk cartitem')
                    cart1=Cart.objects.filter(cart_id__in=[x.cart for x in cartitem1]).first()
                    CartItem.objects.create(user=request.user,product_id=product_id,cart=cart1,price=prod.price)

                    
            else :
                    
                    if Cart.objects.filter(cart_id=cart_sessions(request)).exists():

eccomerce/templates/store/about.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

<main class="pt-90">
    <div class="mb-4 pb-4"></div>
    <section class="contact-us container">
      <div class="mw-930">
        <h2 class="page-title">About US</h2>
      </div>

      <div class="about-us__content pb-5 mb-5">
        <p class="mb-5">
          <img loading="lazy" class="w-100 h-auto d-block" src="/static/assets/images/about/about-1.jpg" width="1410"
            height="550" alt="" />
        </p>
        <div class="mw-930">
          <h3 class="mb-4">OUR STORY</h3>
          <p class="fs-6 fw-medium mb-4">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
            fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
            mollit anim id est laborum.</p>
          <p class="mb-4">Saw wherein fruitful good days image them, midst, waters upon, saw. Seas lights seasons.
            Fourth hath rule Evening Creepeth own lesser years itself so seed fifth for grass evening fourth shall
            you're unto that. Had. Female replenish for yielding so saw all one to yielding grass you'll air sea it,
            open waters subdue, hath. Brought second Made. Be. Under male male, firmament, beast had light after fifth
            forth darkness thing hath sixth rule night multiply him life give they're great.</p>
          <div class="row mb-3">
            <div class="col-md-6">
              <h5 class="mb-3">Our Mission</h5>
              <p class="mb-3">Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>
            <div class="col-md-6">
              <h5 class="mb-3">Our Vision</h5>
              <p class="mb-3">Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>
          </div>
        </div>
        <div class="mw-930 d-lg-flex align-items-lg-center">
          <div class="image-wrapper col-lg-6">
            <img class="h-auto" loading="lazy" src="/static/assets/images/about/about-1.jpg" width="450" height="500" alt="">
          </div>
          <div class="content-wrapper col-lg-6 px-lg-4">
            <h5 class="mb-3">The Company</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet sapien dignissim a elementum. Sociis metus,
              hendrerit mauris id in. Quis sit sit ultrices tincidunt euismod luctus diam. Turpis sodales orci etiam
              phasellus lacus id leo. Amet turpis nunc, nulla massa est viverra interdum. Praesent auctor nulla morbi
              non posuere mattis. Arcu eu id maecenas cras.</p>
          </div>
        </div>
      </div>
    </section>


  </main>

  {% endblock  %}

eccomerce/templates/store/cart.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
<main class="pt-90">
    <div class="mb-4 pb-4"></div>
    <section class="shop-checkout container">
      <h2 class="page-title">Cart</h2>
      <div class="checkout-steps">
        <a href="{% url 'store:cart' %}" class="checkout-steps__item active">
          <span class="checkout-steps__item-number">01</span>
          <span class="checkout-steps__item-title">
            <span>Shopping Bag</span>
            <em>Manage Your Items List</em>
          </span>
        </a>
        <a href="{% url 'store:checkout' %}" class="checkout-steps__item">
          <span class="checkout-steps__item-number">02</span>
          <span class="checkout-steps__item-title">
            <span>Shipping and Checkout</span>
            <em>Checkout Your Items List</em>
          </span>
        </a>
        <a href="{% url 'store:order_confirmation' %}" class="checkout-steps__item">
          <span class="checkout-steps__item-number">03</span>
          <span class="checkout-steps__item-title">
            <span>Confirmation</span>
            <em>Review And Submit Your Order</em>
          </span>
        </a>
      </div>
      <div class="shopping-cart">
        <div class="cart-table__wrapper">
          <table class="cart-table">
            <thead>
              <tr>
                <th>Product</th>
                <th></th>
                <th>Price</th>
                <th>Quantity</th>
             
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for x in cartitem %}
          
              <tr>
                <td>
                  <div class="shopping-cart__product-item">
                    <img loading="lazy" src="{{ x.product.image.url }}" width="120" height="120" alt="" />
                  </div>
                </td>
                <td>
                  <div class="shopping-cart__product-item__detail">
                    <h4>{{x.product.title}}</h4>
                    <!-- <ul class="shopping-cart__product-item__options">
                      <li>Color: Yellow</li>
                      <li>Size: L</li>
                    </ul> -->
                  </div>
                </td>
                <td>
                  <span class="shopping-cart__product-price">Rs {{x.product.price}}</span>
                </td>
                <td>
                  <div class="qty-control position-relative">
                    <input type="number" name="quantity" value="1" min="1" class="qty-control__number text-center increase1">
                    <div class="qty-control__reduce" id="reduce">-</div>
                    <div class="qty-control__increase" id="increase">+</div>
                  </div>
                </td>
                
                <td>
                  <a href="#" class="remove-cart">
                    <svg width="10" height="10" viewBox="0 0 10 10" fill="#767676" xmlns="http://www.w3.org/2000/svg">
                      <path d="M0.259435 8.85506L9.11449 0L10 0.885506L1.14494 9.74056L0.259435 8.85506Z" />
                      <path d="M0.885506 0.0889838L9.74057 8.94404L8.85506 9.82955L0 0.97449L0.885506 0.0889838Z" />
                    </svg>
                  </a>
                </td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
          <div class="cart-table-footer">
            <form action="#" class="position-relative bg-body">
              <input class="form-control" type="text" name="coupon_code" placeholder="Coupon Code">
              <input class="btn-link fw-medium position-absolute top-0 end-0 h-100 px-4" type="submit"
                value="APPLY COUPON">
            </form>
            <!-- <button class="btn btn-light">UPDATE CART</button> -->
          </div>
        </div>
        <div class="shopping-cart__totals-wrapper">
          <div class="sticky-content">
            <div class="shopping-cart__totals">
              <h3>Cart Totals</h3>
              <table class="cart-totals">
                <tbody>
                  <tr>
                    <th>Subtotal</th>
                    <td>Rs <span id="total">{{totalcartitems.product_price}} </span><input type="hidden" id="total_price" class="total_sum" value="{{totalcartitems.product_price}}"></td>
                  </tr>
                  <!-- <tr>
                    <th>Shipping</th>
                    <td>
                      <div class="form-check">
                        <input class="form-check-input form-check-input_fill" type="checkbox" value=""
                          id="free_shipping">
                        <label class="form-check-label" for="free_shipping">Free shipping</label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input form-check-input_fill" type="checkbox" value="" id="flat_rate">
                        <label class="form-check-label" for="flat_rate">Flat rate: $49</label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input form-check-input_fill" type="checkbox" value=""
                          id="local_pickup">
                        <label class="form-check-label" for="local_pickup">Local pickup: $8</label>
                      </div>
                      <div>Shipping to AL.</div>
                      <div>
                        <a href="#" class="menu-link menu-link_us-s">CHANGE ADDRESS</a>
                      </div>
                    </td>
                  </tr> -->
                  <!-- <tr>
                    <th>VAT</th>
                    <td>$19</td>
                  </tr> -->
                  <tr>
                    <th>Total</th>
                    <td><span id="totalgst">Rs {{totalsum}} </span>(inculde 18 % GST)</td>
                  </tr>
                </tbody>
              </table>
            </div>
            {% if user.is_authenticated %}
            <div class="mobile_fixed-btn_wrapper">
              <div class="button-wrapper container">
                <a href="{% url 'store:checkout' %}" class="btn btn-primary btn-checkout">PROCEED TO CHECKOUT</a>
              </div>
            </div>
            {% else %}
            <div class="mobile_fixed-btn_wrapper">
              <div class="button-wrapper container">
                <a href="{% url 'store:login' %}" class="btn btn-primary btn-checkout">PROCEED TO CHECKOUT</a>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </section>
  </main>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script>
     $(document).ready(function () {
    $('#increase').click(function () {
        // Get values from inputs
        var increase = parseInt($('.increase1').val()); // Convert to integer
        var total_price = parseInt($('#total_price').val()); // Convert to integer
 
        // Check if values are valid numbers
        if (!isNaN(increase) && !isNaN(total_price)) {
            var sum = total_price * increase; // Calculate the sum
            $('#total').text(sum);
            totalgst=sum*18/100
            total_sum=sum+totalgst
            $('#totalgst').text(total_sum);
          
        } else {
            alert('Please enter valid numbers.'); // Error message for invalid input
        }
    });

    $('#reduce').click(function () {
        // Get values from inputs
        var increase = parseInt($('.increase1').val()); // Convert to integer
        var total_price = parseInt($('#total_price').val()); // Convert to integer
 
        // Check if values are valid numbers
        if (!isNaN(increase) && !isNaN(total_price)) {
            var sum = total_price * increase; // Calculate the sum
            $('#total').text(sum);
            totalgst=sum*18/100
            total_sum=sum+totalgst
            $('#totalgst').text(total_sum);
          
        } else {
            alert('Please enter valid numbers.'); // Error message for invalid input
        }
    });
    
  });
 </script>



{% endblock %}

eccomerce/templates/store/login.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}








<main class="pt-90">
    <div class="mb-4 pb-4"></div>
    <section class="login-register container">
      <ul class="nav nav-tabs mb-5" id="login_register" role="tablist">
        <li class="nav-item" role="presentation">
          <a class="nav-link nav-link_underscore active" id="login-tab" data-bs-toggle="tab" href="#tab-item-login"
            role="tab" aria-controls="tab-item-login" aria-selected="true">Login</a>
        </li>
      </ul>
      <div class="tab-content pt-2" id="login_register_tab_content">
        <div class="tab-pane fade show active" id="tab-item-login" role="tabpanel" aria-labelledby="login-tab">
          <div class="login-form">
            <form method="POST" action="#" name="login-form" class="needs-validation" novalidate="">
              {% csrf_token %}
              <div class="form-floating mb-3">
                  {{form.email}}
                <label for="email">Email address *</label>
              </div>

              <div class="pb-3"></div>

              <div class="form-floating mb-3">
                 {{form.password}}
                <label for="customerPasswodInput">Password *</label>
              </div>

              <button class="btn btn-primary w-100 text-uppercase" type="submit">Log In</button>

              <div class="customer-option mt-4 text-center">
                <span class="text-secondary">No account yet?</span>
                <a href="{% url 'store:signup' %}" class="btn-text js-show-register">Create Account</a> | <a href="my-account.html"
                  class="btn-text js-show-register">My Account</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  </main>



{% endblock %}

eccomerce/templates/store/order-confirmation.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

<main class="pt-90">
    <div class="mb-4 pb-4"></div>
    <section class="shop-checkout container">
      <h2 class="page-title">Order Received</h2>
      <div class="checkout-steps">
        <a href="{% url 'store:cart' %}" class="checkout-steps__item active">
          <span class="checkout-steps__item-number">01</span>
          <span class="checkout-steps__item-title">
            <span>Shopping Bag</span>
            <em>Manage Your Items List</em>
          </span>
        </a>
        <a href="{% url 'store:checkout' %}" class="checkout-steps__item active">
          <span class="checkout-steps__item-number">02</span>
          <span class="checkout-steps__item-title">
            <span>Shipping and Checkout</span>
            <em>Checkout Your Items List</em>
          </span>
        </a>
        <a href="{% url 'store:order_confirmation' %}" class="checkout-steps__item">
          <span class="checkout-steps__item-number">03</span>
          <span class="checkout-steps__item-title">
            <span>Confirmation</span>
            <em>Review And Submit Your Order</em>
          </span>
        </a>
      </div>
      <div class="order-complete">
        <div class="order-complete__message">
          <svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="40" cy="40" r="40" fill="#B9A16B" />
            <path
              d="M52.9743 35.7612C52.9743 35.3426 52.8069 34.9241 52.5056 34.6228L50.2288 32.346C49.9275 32.0446 49.5089 31.8772 49.0904 31.8772C48.6719 31.8772 48.2533 32.0446 47.952 32.346L36.9699 43.3449L32.048 38.4062C31.7467 38.1049 31.3281 37.9375 30.9096 37.9375C30.4911 37.9375 30.0725 38.1049 29.7712 38.4062L27.4944 40.683C27.1931 40.9844 27.0257 41.4029 27.0257 41.8214C27.0257 42.24 27.1931 42.6585 27.4944 42.9598L33.5547 49.0201L35.8315 51.2969C36.1328 51.5982 36.5513 51.7656 36.9699 51.7656C37.3884 51.7656 37.8069 51.5982 38.1083 51.2969L40.385 49.0201L52.5056 36.8996C52.8069 36.5982 52.9743 36.1797 52.9743 35.7612Z"
              fill="white" />
          </svg>
          <h3>Your order is completed!</h3>
          <p>Thank you. Your order has been received.</p>
        </div>
        <div class="order-info">
          <div class="order-info__item">
            <label>Order Number</label>
            <span>13119</span>
          </div>
          <div class="order-info__item">
            <label>Date</label>
            <span>27/10/2023</span>
          </div>
          <div class="order-info__item">
            <label>Total</label>
            <span>$81.40</span>
          </div>
          <div class="order-info__item">
            <label>Paymetn Method</label>
            <span>Direct Bank Transfer</span>
          </div>
        </div>
        <div class="checkout__totals-wrapper">
          <div class="checkout__totals">
            <h3>Order Details</h3>
            <table class="checkout-cart-items">
              <thead>
                <tr>
                  <th>PRODUCT</th>
                  <th>SUBTOTAL</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    Zessi Dresses x 2
                  </td>
                  <td>
                    $32.50
                  </td>
                </tr>
                <tr>
                  <td>
                    Kirby T-Shirt
                  </td>
                  <td>
                    $29.90
                  </td>
                </tr>
              </tbody>
            </table>
            <table class="checkout-totals">
              <tbody>
                <tr>
                  <th>SUBTOTAL</th>
                  <td>$62.40</td>
                </tr>
                <tr>
                  <th>SHIPPING</th>
                  <td>Free shipping</td>
                </tr>
                <tr>
                  <th>VAT</th>
                  <td>$19</td>
                </tr>
                <tr>
                  <th>TOTAL</th>
                  <td>$81.40</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  </main>

  {% endblock %}